## FreeRADIUS istemci yapılandırması
## Docker ağı (nac_net) üzerindeki tüm IP'lerden bağlantıya izin verir.

client localhost {
	ipaddr = 127.0.0.1
	proto  = *
	secret = $ENV{RADIUS_SECRET}
}

# Docker ağı — tüm konteynerler arası iletişim
client dockernet {
	ipaddr = 172.16.0.0/12
	proto  = *
	secret = $ENV{RADIUS_SECRET}
}
